### ISSUE TITLE
Crossplatform compatibility

### ISSUE THREAD

**Issue by WayfairingStranger** [Swamp-Ig/KSPAPIExtensions#14]
Are there any plans for porting this to Objective-C, or any other language, that can be compiled and run in Mac OS X?

**Comment by NathanKell** [comment]
Eh?
It's a plugin for KSP. It's not a standalone app.

**Comment by WayfairingStranger** [comment]
I understand that it is for KSP.  However it comes with a makefile, which I usually associate with code that needs to be compiled.

**Comment by NathanKell** [comment]
Yes, KSP plugins do need to be compiled to dll. Use MonoDevelop or Xamarin or whatever C# IDE you like. Please see the KSP wiki for information on how to get started making plugins for KSP.

**Comment by NathanKell** [comment]
(If you just want to use this, grab a release and reference it in your plugin. There's not need to compile this yourself, and no need to do _anything_ if you're just an end user. This is for plugin developers. :)    )

**Comment by WayfairingStranger** [comment]
Cool.  I am wanting to use it with TweakScale, and KSPAPIExtensions is required to get TweakScale

**Comment by NathanKell** [comment]
As a user, you don't have to do anything, as I said. All KSP mods that require KSPAPIExtensions _come with_ KSPAPIExtensions already. :)

**Comment by WayfairingStranger** [comment]
Ok, cool.  Thanks for the help.
